"""
Pydantic schemas for request/response validation.

Schemas are different from models:
- Models: SQLAlchemy ORM models (database layer)
- Schemas: Pydantic models (API layer - validation & serialization)

Why separate them:
- Request might not have 'id' or timestamps (generated by database)
- Response includes 'id' and timestamps
- Validation rules can differ (e.g., password hashing for input only)
- Flexibility: database structure != API structure
"""
